services:
  zaim-api:
    build: .
    image: zaim-api-mcp
    environment:
      ZAIM_CONSUMER_KEY: ${ZAIM_CONSUMER_KEY:-}
      ZAIM_CONSUMER_SECRET: ${ZAIM_CONSUMER_SECRET:-}
      ZAIM_ACCESS_TOKEN: ${ZAIM_ACCESS_TOKEN:-}
      ZAIM_ACCESS_TOKEN_SECRET: ${ZAIM_ACCESS_TOKEN_SECRET:-}
    stdin_open: true
